### ISSUE TITLE
Some documentation bugs & feedback

### ISSUE THREAD

**Issue by tlylt** [Berted/coNote#66]
![image](https://user-images.githubusercontent.com/41845017/176918316-6106b172-d191-403d-92b9-2c3426401489.png)

Minor typo

---
> Firebase Limit (Spark plan)
> Using Firebase’s Spark plan as a backend to our collaborative editor could be limiting, as its realtime database for this plan only supports at most 50 simultaneous connections and 100MB of storage.
> As such, if this application is to be deployed at a larger scale, economical considerations would also need to be considered as hosting a real-time collaborative application might prove to be expensive. Perhaps a transition to a peer-to-peer collaborative editor could serve to be more economically effective compared to the current approach.

So how much would it cost if you need to scale up with Firebase? I think including the price information here would be useful.

---

> Response - Absolutely, in terms of features, applications like Notion definitely take the cake over ours. I'd say our biggest advantage is pricing and open code base. As our services currently uses free hosting (i.e. Firebase Spark plan and Vercel), we can charge no price to the customer for using collaborative features (Notion charges users for collaborative features and so does HackMD for some features). Whilst this may no longer be true with more users, our open code base allows small groups to set up their own deployment for free with only minimal time investment and even add their own features. In order to achieve this, we aim to better re-write our codebase along with more robust documentation.

Just a minor point on Notion: I think collaborating on notion pages is actually free-of-charge, so the point made is not accurate

**Comment by Berted** [comment]
Hi, we have resolved all these issues in our latest (not yet complete) [Milestone 3 submission](https://co-note.vercel.app/docs/-N6lsluWWc5RQFABhg8C). Thanks for the feedback!
