### ISSUE TITLE
Consider making a demo markdown note available in the user's collection

### ISSUE THREAD

**Issue by tlylt** [Berted/coNote#69]
Either create a demo markdown note (I think you guys have a demo markdown note before, but I can't seem to find it anymore) or have a way for non-login/logged-in users to easily view the demo file. I think it will be a good idea for showcasing the syntax and the capabilities of the website. May also be helpful for testing.

**Comment by Berted** [comment]
Being worked on, see https://co-note.vercel.app/docs/-N7_A0yVxAjjB-jtlQaN.

**Comment by Berted** [comment]
Ready for now, albeit the code isn't as maintainable for now.
