### ISSUE TITLE
Modification seems too sensitive

### ISSUE THREAD

**Issue by tlylt** [Berted/coNote#79]
It seems like as long as I touch the input box, the system considers me to have modified the document, which I did not do so. Wonder if it is possible to track that a real change has been done before we update that a document is modified
![image](https://user-images.githubusercontent.com/41845017/178129623-34bf86f4-e21f-4d6f-a060-32452a27e3bc.png)

**Comment by Berted** [comment]
Hi, it seems that #73 was incorrectly marked as resolved as an incorrect merge occurred when merging multiple branches to the main branch. It should be resolved now with commit 2ea2108fc71e7bfe41713e2e496667b85281bbbe. Thanks!
